repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        stages: [commit]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.9.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@open-turo/commitlint-config-conventional"]
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.17
    hooks:
      - id: actionlint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        exclude: "^files/(.zshrc|.p10k.zsh)$"
      # - id: shfmt
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        args:
          [
            --ignore,
            DL3008,
            --ignore,
            DL3059,
            --ignore,
            SC3037,
            --ignore,
            DL4006,
          ]
  # Use go vet from the default hooks instead
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.2
    hooks:
      - id: go-mod-tidy
      - id: go-vet
      - id: go-fmt
  # - repo: https://github.com/golangci/golangci-lint
  #   rev: v1.55.2
  #   hooks:
  #     - id: golangci-lint-full
