repos:
  - repo: https://github.com/turo/pre-commit-hooks
    rev: v3.4.2
    hooks:
    - id: go-mod-tidy
    - id: go-build
    - id: golangci-lint
    - id: go-test-unit
    - id: gomarkdoc
    # - id: docker-lint  # Getting in the way
    - id: docker-compose-lint
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ["@open-turo/commitlint-config-conventional"]
