#!/bin/dash -e
# Install or upgrade
$RUN brew "$( { [ -z "$UPGRADE" ] && echo "install"; } || echo "upgrade" )" "$NAME"
# shellcheck disable=SC2046
$RUN ln -sf $(brew --prefix)/opt/python/libexec/bin/* /usr/local/bin/
