#!/bin/dash -e
# Direct install
# $RUN curl -o "$TMP" -fsSL "https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh"
# $RUN /bin/bash "$TMP"

# Install or upgrade
$RUN brew "$( { [ -z "$UPGRADE" ] && echo "install"; } || echo "upgrade" )" "$NAME"
$RUN /bin/dash -c "mkdir -p $HOME/.bin && ln -sf /bin/dash $HOME/.bin/$NAME"
