#!/bin/dash -e
# Install or upgrade
$RUN brew "$( { [ -z "$UPGRADE" ] && echo "install"; } || echo "upgrade" )" "$NAME"
if [ -x "$(command -v fdfind)" ]; then $RUN ln -sf "$(command -v fdfind)" "$HOME/.bin/fd"; fi
