#!/bin/dash -e
# Install or upgrade
$RUN brew "$( { [ -z "$UPGRADE" ] && echo "install"; } || echo "upgrade" )" "$NAME"
# Enable dash to use pyenv
$RUN echo "PYENV_ROOT=$(pyenv root)" | sudo tee -a /etc/profile
$RUN echo "eval \"\$(pyenv init -)\"" | sudo tee -a /etc/profile
