#!/bin/dash -e

# Install Powerline fonts

# Clone the powerline repo
$RUN git clone https://github.com/powerline/fonts.git --depth=1 "$TMP/powerline"
# Install the fonts
$RUN "$TMP/powerline/install.sh"


# Install NerdFonts

# Clone the nerd-fonts repo
$RUN git clone https://github.com/ryanoasis/nerd-fonts.git --depth=1 "$TMP/nerd-fonts"
# Install the fonts
$RUN "$TMP/nerd-fonts/install.sh"


# Make the dummy 'fonts' executable for install checking
$RUN /bin/dash -c "mkdir -p $HOME/.bin && ln -sf /bin/dash $HOME/.bin/$NAME"
