#!/bin/sh
# Global commit-msg hook using prek
# https://github.com/j178/prek

# Exit quietly if prek isn't installed
command -v prek >/dev/null 2>&1 || exit 0

# Run commit-msg hooks via prek
# $1 is the path to the commit message file
exec prek run --hook-stage commit-msg --commit-msg-filename "$1"
