#!/bin/sh
echo "prepare-commit-msg"
# Exit quietly if cz doesn't exist
[ -x "$(command -v cz)" ] || exit 0
echo "found cz"
# Prevent issues when rebasing
[ "$1"  = ".git/COMMIT_EDITMSG" ] && [ "$2" = "message" ] && exit 0
echo "not rebasing"
# Run the commitizen script
exec < /dev/tty && cz --hook || true
echo "script ran $?"