#!/bin/dash -e
# brew is special and needs sudo
$RUN sudo --non-interactive --validate || $RUN sudo --validate
$RUN curl -o "$TMP" -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
$RUN /bin/bash "$TMP"

# Ensure brew is in PATH in dash shell
if ! $RUN grep 'brew' /etc/profile; then
    $RUN echo "export PATH=\"$($RUN brew --prefix)/bin:\$PATH\"" | $RUN sudo tee -a "/etc/profile"
fi
