#!/bin/dash -e
# brew is special and needs sudo
$RUN sudo --non-interactive --validate || $RUN sudo --validate
$RUN curl -o "$TMP" -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
$RUN /bin/bash "$TMP"

# Ensure brew is in PATH in dash shell
if [ -z "$DRY_RUN" ]; then
    if ! grep 'brew' /etc/profile >/dev/null 2>&1; then
        echo "export PATH=\"$(brew --prefix)/bin:\$PATH\"" | sudo tee -a "/etc/profile"
    fi
fi
