#!/bin/dash -e
# Install or upgrade
$RUN brew "$( { [ -z "$UPGRADE" ] && echo "install"; } || echo "upgrade" )" "$NAME"
# Enable dash to use pyenv
if [ -z "$DRY_RUN" ]; then
    if ! grep 'pyenv' /etc/profile >/dev/null 2>&1; then
        echo "PYENV_ROOT=\$(pyenv root)" | sudo tee -a /etc/profile
        echo "[ ! command -v pyenv >/dev/null 2>&1 ] || eval \"\$(pyenv init -)\"" | sudo tee -a /etc/profile
    fi
fi

# This saves us the time of compiling Python on codespace startup
$RUN echo "Installing global Python version"
$RUN brew "$( { [ -z "$UPGRADE" ] && echo "install"; } || echo "upgrade" )" "python@3.12"
