#!/bin/dash -e
# Install or upgrade
$RUN brew "$( { [ -z "$UPGRADE" ] && echo "install"; } || echo "upgrade" )" "$NAME"

# Install node16 by default
if command -v nodenv &>/dev/null; then
	eval "$(nodenv init -)"
	eval "$(nodenv init --path)"
	nodenv install 16.13.2
	nodenv global 16.13.2
fi
