#!/bin/dash -e
# Install or upgrade
$RUN brew "$( { [ -z "$UPGRADE" ] && echo "install"; } || echo "upgrade" )" "$NAME"

$RUN echo "Installing Golang packages for IDE"
$RUN go install golang.org/x/tools/gopls@latest
$RUN go install github.com/cweill/gotests/gotests@v1.6.0
$RUN go install github.com/fatih/gomodifytags@v1.16.0
$RUN go install github.com/josharian/impl@v1.1.0
$RUN go install github.com/haya14busa/goplay/cmd/goplay@v1.0.0
$RUN go install github.com/go-delve/delve/cmd/dlv@latest
$RUN go install honnef.co/go/tools/cmd/staticcheck@latest
