#!/bin/dash -e
# Install or upgrade
$RUN brew "$( { [ -z "$UPGRADE" ] && echo "install"; } || echo "upgrade" )" "$NAME"
# Enable dash to use goenv
if [ -z "$DRY_RUN" ]; then
    if ! grep 'goenv' /etc/profile >/dev/null 2>&1; then
        echo "GOENV_ROOT=\$(goenv root)" | sudo tee -a /etc/profile
        echo "[ ! command -v goenv >/dev/null 2>&1 ] || eval \"\$(goenv init -)\"" | sudo tee -a /etc/profile
    fi
fi

$RUN echo "Installing global Golang version"
$RUN eval "$(goenv init -)"
$RUN goenv install 1.21.4
$RUN goenv install 1.20.11
$RUN goenv global 1.20.11

$RUN echo "Installing Golang packages for IDE"
$RUN go install golang.org/x/tools/gopls@latest
$RUN go install github.com/cweill/gotests/gotests@v1.6.0
$RUN go install github.com/fatih/gomodifytags@v1.16.0
$RUN go install github.com/josharian/impl@v1.1.0
$RUN go install github.com/haya14busa/goplay/cmd/goplay@v1.0.0
$RUN go install github.com/go-delve/delve/cmd/dlv@latest
$RUN go install honnef.co/go/tools/cmd/staticcheck@latest
