#!/bin/dash -e
# Install or upgrade
$RUN brew "$( { [ -z "$UPGRADE" ] && echo "install"; } || echo "upgrade" )" "$NAME"
# To install useful key bindings and fuzzy completion:
# shellcheck disable=SC2046
$RUN $($RUN brew --prefix)/opt/fzf/install
