name: Release

# on:
#   push:
#     branches: [main]

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  semantic-release:
    name: Semantic release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: open-turo/actions-release/semantic-release@v4
        with:
          github-token: ${{ secrets.GHA_TOKEN }}
