name: Release

on:
  push:
    branches: [main]

jobs:
  semantic-release:
    name: Semantic release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: open-turo/actions-release/semantic-release@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
